# Generated by Django 4.2.9 on 2025-03-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahall',
            name='capacity',
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='seats',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
