# Generated by Django 4.2.9 on 2025-03-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_remove_cinemahall_capacity_cinemahall_seats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CinemaHall',
        ),
    ]
